/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arreglos;
//para el manejo de arreglos
import java.util.Arrays;

/**
 *
 * @author jdextre
 */
public class calcularNotas extends javax.swing.JFrame {

    /**
     * Creates new form calcularNotas
     */
    public calcularNotas() {
        initComponents();
       
   
        this.setSize(460,360);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtn2 = new javax.swing.JTextField();
        txtresultado = new javax.swing.JTextField();
        txtn1 = new javax.swing.JTextField();
        txtn3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtn4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Notas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 170, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nota 1 :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 80, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nota 2 : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nota 3 : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 80, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Resultado :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 260, 80, 20);
        getContentPane().add(txtn2);
        txtn2.setBounds(140, 110, 120, 30);
        getContentPane().add(txtresultado);
        txtresultado.setBounds(140, 260, 120, 30);
        getContentPane().add(txtn1);
        txtn1.setBounds(140, 70, 120, 30);
        getContentPane().add(txtn3);
        txtn3.setBounds(140, 150, 120, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nota 4 :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 200, 80, 20);
        getContentPane().add(txtn4);
        txtn4.setBounds(140, 190, 120, 30);

        jButton1.setText("Menor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 160, 100, 23);

        jButton2.setText("Promedio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 70, 100, 23);

        jButton3.setText("Sumar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 100, 100, 23);

        jButton4.setText("Mayor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 130, 100, 23);

        jButton5.setText("Ordenar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 200, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           int notas[] = new int[4];
        notas[0] = Integer.parseInt(txtn1.getText());
        notas[1] = Integer.parseInt(txtn2.getText());
        notas[2] = Integer.parseInt(txtn3.getText());
        notas[3] = Integer.parseInt(txtn4.getText());
        //declarar una variable de tipo mayor
        int menor=100;
        for (int i=0;i<notas.length;i++) {
                    if (notas[i]<menor) {
                    menor = notas[i];
                    }
                    
            }
          txtresultado.setText(String.valueOf(menor));
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int notas[] = new int[4];
        notas[0] = Integer.parseInt(txtn1.getText());
        notas[1] = Integer.parseInt(txtn2.getText());
        notas[2] = Integer.parseInt(txtn3.getText());
        notas[3] = Integer.parseInt(txtn4.getText());
        //int resultado = Integer.parseInt(txtresultado.getText());
        double totalNotas=0;
        for (int x=0;x<notas.length;x++) {
            totalNotas+=notas[x];
        }
        double promedio = totalNotas/notas.length;
        txtresultado.setText(String.valueOf(promedio));
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int notas[] = new int[4];
        notas[0] = Integer.parseInt(txtn1.getText());
        notas[1] = Integer.parseInt(txtn2.getText());
        notas[2] = Integer.parseInt(txtn3.getText());
        notas[3] = Integer.parseInt(txtn4.getText());
        int sumarNotas=0;
        for (int nota: notas) {
        sumarNotas+=nota;
        }
        txtresultado.setText(String.valueOf(sumarNotas));
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           int notas[] = new int[4];
        notas[0] = Integer.parseInt(txtn1.getText());
        notas[1] = Integer.parseInt(txtn2.getText());
        notas[2] = Integer.parseInt(txtn3.getText());
        notas[3] = Integer.parseInt(txtn4.getText());
        //declarar una variable de tipo mayor
        int mayor=0;
        for (int i=0;i<notas.length;i++) {
                    if (notas[i]>mayor) {
                    mayor = notas[i];
                    }
                    
            }
          txtresultado.setText(String.valueOf(mayor));
          
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int notas[] = new int[4];
        notas[0] = Integer.parseInt(txtn1.getText());
        notas[1] = Integer.parseInt(txtn2.getText());
        notas[2] = Integer.parseInt(txtn3.getText());
        notas[3] = Integer.parseInt(txtn4.getText());
        Arrays.sort(notas);
       System.out.println(Arrays.toString(notas));
        //txtresultado.setText(Arrays.sort(notas));
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcularNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcularNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    private javax.swing.JTextField txtn4;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
